var notice_202211 = 
"<div class='popupTitle' style='text-align: center; padding-bottom: 1em'> 2022년 11월 업데이트 안내 (2022-11-04)</div>"
+"<ul>"
+"<li><div class='notice'>2019년 1월부터의 월별 평균 실거래가 정보를 그래프와 함께 표시합니다.</div></li>"
+"<li><div class='notice'>월별 평균 실거래가 정보의 기간을 선택하여 매매가 등락률을 확인할 수 있도록 했습니다.</div></li>"
+"<li><div class='notice'>'서울시 송파구'의 한강 프리미엄 적용 범위를 800m → 1200m로 확장 적용 했습니다. (아파트 단지 크기 고려)</div></li>"
+"<li><div class='notice'>'경기도 김포시'의 누락되었던 '김포골드라인 마산역' 정보를 추가했습니다.</div></li>"
+"<li><div class='notice'>단지 정보 우측 하단의 공유하기 버튼을 통해 단지 정보 공유 후, 해당 링크 선택 시 단지 목록만 표시되던 것을 해당 단지의 상세정보 팝업이 표시되도록 했습니다.</div></li>"
+"<li><div class='notice'>KB월간 시계열 기준 10월 시군구 정보 반영했습니다.</div></li>"
+"</ul>"      
+"<hr>"

var notice_202210 = 
"<div class='popupTitle' style='text-align: center; padding-bottom: 1em'> 2022년 10월 업데이트 안내 (2022-10-07)</div>"
+"<ul>"
+"<li><div class='notice'>인프라의 '쇼핑몰'에 'AK&'과 '이케아'를 추가했습니다.</div></li>"
+"<li><div class='notice'>10월 인구 변동 정보 업데이트 했습니다.</div></li>"
+"<li><div class='notice'>지역구의 일자리 수 정보 업데이트 했습니다. (통계청 제공)</div></li>"
+"<li><div class='notice'>KB월간 시계열 기준 9월 시군구 정보 반영했습니다.</div></li>"
+"</ul>"      
+"<hr>"

var notice_202209 = 
"<div class='popupTitle' style='text-align: center; padding-bottom: 1em'> 2022년 9월 업데이트 안내 (2022-09-07)</div>"
+"<ul>"
+"<li><div class='notice'>전국 시군구의 공급량 및 적정공급량을 인근지역 공급량을 합산하여 산정했습니다.</div></li>"
+"<li><div class='notice'>분양 예정 단지 정보 추가하였으며, 확정되지 않은 정보들을 포함하고 있습니다.</div></li>"
+"<li><div class='notice'>인프라의 '대형마트'에 '이마트트레이더스'와 '빅마켓'을 추가했습니다.</div></li>"
+"<li><div class='notice'>9월 인구 변동 정보 업데이트 했습니다.</div></li>"
+"<li><div class='notice'>은행 정보 업데이트 했습니다. (전국은행연합회 제공)</div></li>"
+"<li><div class='notice'>초등학교 정보 업데이트 했습니다. (교육통계서비스 제공)</div></li>"
+"<li><div class='notice'>KB월간 시계열 기준 8월 시군구 정보 반영했습니다.</div></li>"
+"</ul>"      
+"<hr>"

var notice_202208 = 
"<div class='popupTitle' style='text-align: center; padding-bottom: 1em'> 2022년 8월 업데이트 안내 (2022-08-05)</div>"
+"<ul>"
+"<li><div class='notice'>수도권 및 광역시에 '층간 소음 관리' 정보 추가했습니다. (<span style='color:#4542f5; font-weight:600'>주거문화개선연구소</span> 제공)</div></li>"
+"<li><div class='notice'>8월 인구 변동 정보 업데이트 했습니다.</div></li>"
+"<li><div class='notice'>병원 정보 업데이트 했습니다. (건강보험심사평가원 제공)</div></li>"
+"<li><div class='notice'>KB월간 시계열 기준 7월 시군구 정보 반영했습니다.</div></li>"      
+"</ul>"      
+"<hr>"

var notice_202207 = 
"<div class='popupTitle' style='text-align: center; padding-bottom: 1em'> 2022년 7월 2차 업데이트 안내 (2022-07-27)</div>"
+"<ul>"
+"<li><div class='notice'>7월 25일자 데이터로 전체 업데이트 했습니다.</div></li>"
+"<li><div class='notice'>'서울시 동대문구'의 청량리역 반경이 넓은 이유로 중심점 거리 오류 제보를 반영하여 일부 단지의 역세권 여부 수정했습니다.</div></li>"
+"</ul>"
+"<hr>"
+"<div class='popupTitle' style='text-align: center; padding-bottom: 1em'> 2022년 7월 1차 업데이트 안내 (2022-07-03)</div>"
+"<ul>"
+"<li><div class='notice'>역세권 판단 거리를 가까운 역출구와의 거리로 재산정 했습니다.</div></li>"
+"<li><div class='notice'>300m 이내의 유흥시설, 모텔 정보를 반영하여 '교육'의 감점요소로 적용했습니다.</div></li>"
+"</ul>"
+"<hr>"

var notice_202206 = 
"<div class='popupTitle' style='text-align: center; padding-bottom: 1em'> 2022년 6월 2차 업데이트 안내 (2022-06-18)</div>"
+"<ul>"
+"<li><div class='notice'> 내가 원하는 정보를 입력하여 랭크와 점수를 확인하는 <br><span style='font-weight: 600; color: #fe4040;'>[랭크 시뮬레이션 (BETA)]</span> 기능을 추가했습니다.</div></li>"
+"<li><div class='notice'> <span style='font-weight: 600; color: #fe4040;'>[랭크 시뮬레이션 (BETA)]</span>는 아파트 단지 선택 후, 종합 순위 하단의 버튼을 눌러 사용할 수 있습니다.</div></li>"
+"<li><div><img src='https://www.aptrank.kr/rank_simulation_202206.jpg' width='70%'/></div></li>"
+"<li><div class='notice'> 2022년 6월 18일자 네이버 부동산 데이터 적용했습니다.</div></li>"
+"<li><div class='notice'> 단지별 기본 표시 주소를 도로명주소에서 법정동주소로 변경했습니다.</div></li>"
+"<li><div class='notice'> 누락되었던 8호선 '남위례'역을 추가했습니다.</div></li>"
+"</ul>"
+"<hr>"
+"<div class='popupTitle' style='text-align: center; padding-bottom: 1em'> 2022년 6월 업데이트 안내 (2022-06-04)</div>"
+"<ul>"
+"<li><div class='notice'> 지역 변경 시 가중치를 설정하는 팝업을 표시하도록 했습니다. (표시하지 않기 선택 가능)</div></li>"
+"<li><div class='notice'> 신림선 역정보 추가했습니다.</div></li>"
+"<li><div class='notice'> 서울시에 '한강 프리미엄'에 대한 가점 로직을 적용했습니다.</div></li>"
+"<li><div class='notice'> 부산시에 '해운대 프리미엄'에 대한 가점 로직을 적용했습니다.</div></li>"
+"<li><div class='notice'> '인프라' 항목에 '대형공원' 정보 및 계산 로직을 추가했습니다.</div></li>"
+"<li><div class='notice'> 아울렛/몰에 '스타필드' 및 '스타필드 시티' 추가했습니다.</div></li>"
+"<li><div class='notice'> 누락되었던 1호선 '중동'역을 추가했습니다(경기도 부천시 반영).</div></li>"
+"<li><div class='notice'> 좌측 상단의 '정렬' 기능을 개선 적용했습니다. (정렬 시 기존 순위가 유지되었던 것을 새로운 정렬에 맞도록 수정)</div></li>"      
+"</ul>"
+"<hr>"

var notice_202205 =
"<div class='popupTitle' style='text-align: center; padding-bottom: 1em'> 2022년 5월 업데이트 안내 (2022-05-04)</div>"
+"<ul>"
+"<li><div class='notice'> 도시형 생활주택을 단지 목록에서 제거했습니다.</div></li>"
+"<li><div class='notice'> 서울과 수도권 주요역까지의 이동 시간을 '목요일 오전 8:30분' 출발시간으로 설정하여 일괄 재계산 했습니다.</div></li>"
+"<li><div class='notice'> 초등학교와의 거리 정보를 교육 점수에 반영했습니다.</div></li>"
+"<li><div class='notice'> 학원가와의 거리, 학원의 개수를 교육 점수에 반영했습니다.</div></li>"
+"<li><div class='notice'> 수인분당/신분당선 '미금'역의 좌표 오류 수정 반영했습니다.</div></li>"
+"<li><div class='notice'> 누락되었던 서해선 '신천'역을 추가했습니다.</div></li>"
+"<li><div class='notice'> 누락되었던 3호선 '화정', '대곡'역을 추가했습니다.</div></li>"
+"<li><div class='notice'> 누락되었던 2호선 '종합운동장'역을 추가했습니다.</div></li>"
+"<li><div class='notice'> 경기도 화성시 대형 쇼핑몰인 '타임테라스'를 추가했습니다.</div></li>"
+"<li><div class='notice'> 상권의 개수와 점포 수를 인프라 점수에 반영했습니다.</div></li>"
+"<li><div class='notice'> 서울, 부산 지역 '균형잡힌 가중치'의 '주거'를 상향하고 '교통'을 하향했습니다.</div></li>"
+"<li><div class='notice'> 광주, 대전, 대구 지역 '균형잡힌 가중치'의 '교육'을 상향하고 '교통'을 하향했습니다.</div></li>"
+"<li><div class='notice'> 혐오시설에 열병합발전소, 교정시설을 추가했습니다.</div></li>"
+"<li><div class='notice'> 3차에 걸친 4월 업데이트로 인해, 5월 순위 변동량이 일부 맞지 않을 수 있습니다.</div></li>"
+"</ul>"
+"<hr>"

var notice_202204 = 
"<div class='popupTitle' style='text-align: center; padding-bottom: 1em'> 2022년 4월 3차 업데이트 안내 (2022-04-19)</div>"
+"<ul>"
+"<li><div class='notice'> 단지 년차 계산 시, 당해년도를 제외하여 1년씩 년차를 줄였습니다.</div></li>"
+"<li><div class='notice'> '경기도 용인시 수지구'의 역세권 계산 시, 누락된 '동천역(신분당선)'을 추가하고, 주요 역 이동 시간을 재계산 했습니다. (Google API 사용)</li></div>"
+"<li><div class='notice'> '서울시 성동구' 아파트 단지의 주요 역 이동시간을 재계산 했습니다. (입지 분석 결과에 대한 의문점 개선. Google API 사용)</li></div>"
+"<li><div class='notice'> '경기도 광명시' 아파트 단지의 주요 역 이동시간을 재계산 했습니다. (입지 분석 결과에 대한 의문점 개선. Google API 사용)</li></div>"
+"<li><div class='notice'> '경기도 하남시' 아파트 단지의 주요 역 이동시간을 재계산 했습니다. (입지 분석 결과에 대한 의문점 개선. Google API 사용)</li></div>"      
+"</ul>"
+"<hr>"
+"<div class='popupTitle' style='text-align: center; padding-bottom: 1em'> 2022년 4월 2차 업데이트 안내</div>"
+"<ul>"
+"<li><div class='notice'> 분양권, 재건축 진행 중인 아파트 단지 추가되었습니다.</div></li>"
+"<li><div class='notice'> 기존 30년 이상 단지에 '재건축 대상' 계산 방식을 삭제하고, '재건축 진행' 단지에만 용적률, 건폐율 계산방식을 적용했습니다.</li></div>"
+"<li><div class='notice'> 30년 이상 단지에 대해 용적률, 건폐율 계산방식 적용이 필요하시면 카카오톡 1:1 문의하기로 의견 부탁드립니다.</li></div>"
+"</ul>"
+"<hr>"

+"<div class='popupTitle' style='text-align: center; padding-bottom: 1em'> 2022년 4월 1차 업데이트 안내</div>"
+"<ul>"
+"<li><div class='notice'> 아파트랭크 앱이 제작되었습니다.(안드로이드 전용)<br>하단의 <a href='https://play.google.com/store/apps/details?id=com.aptrank.app' target='_blank'>'앱 설치하기'</a> 버튼을 통해 다운로드 가능합니다.</li></div>"
+"<li><div class='notice'> 아파트랭크 카카오톡 채널을 개설했습니다. 업데이트 정보는 카카오톡 채널을 통해 전달됩니다. <br>하단의 <a href='http://pf.kakao.com/_vESNb' target='_blank'>'카카오톡 채널로 업데이트 소식받기'</a> 버튼을 눌러 채널을 추가해 주세요.</li></div>"
+"<li><div class='notice'> 형평성 문제가 제기되어 80세대 이하의 단지를 통계에서 제외했습니다.</li></div>"
+"<li><div class='notice'> 아파트 단지별 평형별 실거래가, 주차대수, 세대당 주차수, 평균 관리비, 난방방식 정보를 추가했습니다.</div></li>"
+"<li><div class='notice'> 수도권 4호선 진접선 정보 추가했습니다.</div></li>"
+"<li><div class='notice'> 전국 지역구별 매매/전세 가격 지수 정보를 추가했습니다.</div></li>"
+"<li><div class='notice'> 인구 정보 업데이트 되었습니다.</li></div>"
+"<li><div class='notice'> 은행 정보 업데이트되어 반영했습니다.</li></div>"
+"<li><div class='notice'> 병원 정보 업데이트 반영했으며, 한방병원 정보가 추가되었습니다.</li></div>"
+"<li><div class='notice'> 공원 위치 정보 업데이트되어 반영했습니다.</li></div>"
+"<li><div class='notice'> 지역별 미분양을 포함한 공급량 데이터 업데이트 반영했습니다. </li></div>"
+"<li><div class='notice'> 소득, 백화점, 초등학교 정보는 지난달과 동일합니다.</li></div>"
+"</ul>"
+"<hr>"

var notice_202203 = 
"<div class='popupTitle' style='text-align: center; padding-bottom: 1em'> 2022년 3월 업데이트 안내</div>"
+"<ul>"
+"<li><div class='notice'> [2022년 3월 8일] 수도권 7호선에 누락된 '산곡'역을 추가하여 인천 부평구 및 서구 랭크를 재등록 했습니다. </div></li>"
+"<li><div class='notice'> 가격 필터 기능을 추가했습니다. 우측 상단의 설정 아이콘을 눌러 확인할 수 있습니다.</div></li>"
+"<li><div class='notice'> 2030년까지 개통 예정인 역들을 추가하여 역세권을 계산합니다.</div></li>"
+"<li><div class='notice'> 수도권 주요 거점역에 GTX-A 예정 노선인 킨텍스역, 동탄역, 용인역을 추가했습니다.</li></div>"
+"<li><div class='notice'> 부산, 대구, 대전, 광주의 주요 거점역을 확대 적용했습니다.</li></div>"
+"<li><div class='notice'> 통계에 제외된 100세대 이하 단지를 50세대 이하 단지로 변경했습니다.</li></div>"
+"<li><div class='notice'> 지역별 일자리 통계 업데이트 되었습니다.</li></div>"
+"<li><div class='notice'> 유해시설 위치 정보 업데이트되어 반영했습니다.</li></div>"
+"<li><div class='notice'> 공원 위치 정보 업데이트되어 반영했습니다.</li></div>"
+"<li><div class='notice'> 지역별 미분양을 포함한 공급량 데이터 업데이트 반영했습니다. </li></div>"
+"<li><div class='notice'> 인구, 소득, 백화점, 은행, 병원, 초등학교 정보는 지난달과 동일합니다.</li></div>"
+"</ul>"
+"<hr>"